version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: testdb
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

volumes:
  postgres_data: