openapi: "3.1.0"
info:
  title: "PersonsFinder API"
  description: "PersonsFinder API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /api/v1/persons:
    post:
      summary: "POST api/v1/persons"
      operationId: "createPerson"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePersonRequest"
        required: true
      responses:
        "201":
          description: "Person created successfully"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PersonDto"
        "400":
          description: "Bad Request"

components:
  schemas:
    CreatePersonRequest:
      type: "object"
      properties:
        name:
          type: "string"
      required:
        - "name"
    PersonDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
      required:
        - "id"
        - "name"